#page title
page_title                                : FUT 25 Card Creator                                        # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 6475289123                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                         # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : FUT 25 Card Creator                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : We are proud to introduce the Free FUT 25 Card Creator, The best Card Creator App.


enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Player Creator App                                
your_link                                 :                      
your_city                                 : America                                
email_address                             : scooter48954@gmail.com
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : 
github_username                           :
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : The simplest creator
    description                           : You can create a great playercard with just 3 clicks
    fontawesome_icon_name                 : star
    
  - title                                 : Save and share
    description                           : You can save the created cards in your local gallery and share them in the APP or on other social media.
    fontawesome_icon_name                 : star

  - title                                 : Fun community features
    description                           : You can share the player cards you created in the APP community and interact with each player.
    fontawesome_icon_name                 : star

  - title                                 : Cutting-edge fc25 news
    description                           : You can receive and view the latest FC24 news.
    fontawesome_icon_name                 : star

  - title                                 : Absolutely no ads
    description                           : You can use this APP for free without any restrictions.
    fontawesome_icon_name                 : star
  
#   - title                                 : Feature List
#     description                           : Add features (like this one) to your site via the _config.yml file. No HTML/CSS needed.
#     fontawesome_icon_name                 : star

#   - title                                 : Smart App Banner
#     description                           : Display a smart app banner on iOS devices.
#     fontawesome_icon_name                 : arrow-alt-circle-down

#   - title                                 : Social Links
#     description                           : Easily add social media accounts and contact info in the footer via the _config.yml file. No HTML/CSS needed.
#     fontawesome_icon_name                 : link

#   - title                                 : FontAwesome Support
#     description                           : Pick custom Font Awesome icons for the feature list via the _config.yml file. No HTML/CSS needed.
#     fontawesome_icon_name                 : info-circle

#   - title                                 : # New Feature Title
#     description                           : # New Feature Description
#     fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#22E569"
feature_icons_background_color            : "#F5F6FA"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
